name: Deploy Server

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy
      run: |
        cd ~/aiccmap_project/server && \
        git pull && \
        docker stop server_container || true && \
        docker rm server_container || true && \
        docker build -t server_image . && \
        docker run -d --name server_container -p 5000:5000 server_image
        
