name: Deploy Server via Bastion

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: SSH into Client (Bastion) and deploy to Server
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > client_key.pem
        echo "${{ secrets.EC2_SERVER_KEY }}" > server_key.pem
        chmod 400 client_key.pem server_key.pem

        # 클라이언트 인스턴스(퍼블릭)에 먼저 SSH 접속
        ssh -o StrictHostKeyChecking=no -i ./client_key.pem -A -t ${{ secrets.AWS_EC2_USER }}@${{ secrets.CLIENT_PUBLIC_IP }} "\
          ssh -o StrictHostKeyChecking=no -i ./server_key.pem ${{ secrets.AWS_EC2_USER }}@${{ secrets.SERVER_PRIVATE_IP }} \
          'cd ~/aicc_project/server && git pull && \
          docker stop server_container || true && \
          docker rm server_container || true && \
          docker build -t server_image . && \
          docker run -d --name server_container -p 5000:5000 server_image'"
